### ISSUE TITLE
`Unknown opcode 192` - prestine contract code does not compile

### ISSUE THREAD

**Issue by peetzweg** [paritytech/cargo-contract#1193] opened 2023-07-04 13:00 UTC
After I upgraded my local installation of rust and `cargo-contract`, the `cargo contract new` contract does not build for me. I get the following error message:

```
ERROR: Loading of original wasm failed

Caused by:
    0: Loading of wasm module at '/Users/ppoloczek/fresh/target/ink/wasm32-unknown-unknown/release/fresh.wasm' failed
    1: Unknown opcode 192
```

I've updated my setup with these commands:
`rustup update`
`cargo install --force --locked cargo-contract`

I'm on these version now:
```
rustc 1.70.0 (90c541806 2023-05-31)
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
cargo-contract 3.0.1-unknown-aarch64-apple-darwin
```

---

<img width="1512" alt="Screenshot 2023-07-04 at 14 54 54" src="https://github.com/paritytech/cargo-contract/assets/839848/1114fc50-a315-47b2-9142-61877b16c9c6">
<img width="1512" alt="Screenshot 2023-07-04 at 14 55 25" src="https://github.com/paritytech/cargo-contract/assets/839848/56470f01-ac1b-450f-9cbd-90b9e9474bf1">

**Comment by peetzweg** [comment] 2023-07-04 13:16
Works on rustc 1.69.0 .

**Comment by ascjones** [comment] 2023-07-04 14:18
Yes you have to use `1.69`

This is a duplicate of https://github.com/paritytech/cargo-contract/issues/1139

It's been fixed in https://github.com/paritytech/cargo-contract/pull/1189 (still to be released), but you would still need to use `1.69` because `pallet-contracts` also does not support that op code

**Comment by statictype** [comment] 2023-07-17 17:38
just got this error today with `1.71`. switched to `1.69` and works fine.

**Comment by statictype** [comment] 2023-07-17 18:03
Ok, missed this part: still to be released

**Closed by statictype** 2023-07-17 18:03 UTC
Labels: bug
