### ISSUE TITLE
ERROR: Loading of original wasm failed

### ISSUE THREAD

**Issue by virgil2019** [paritytech/cargo-contract#1156] opened 2023-06-11 06:04 UTC
When building ink! example flipper, I encountered the problem:

```
ERROR: Loading of original wasm failed

Caused by:
    0: Loading of wasm module at '/home/george/test/test/ink/flip40/target/ink/wasm32-unknown-unknown/release/flip40.wasm' failed
    1: Unknown opcode 192
```

[Environment]
Ubuntu 20.04, Ubuntu 20.04 WSL
cargo-contract-contract 3.0.1-unknown-x86_64-unknown-linux-gnu
SDK: 4.2.0
rust: stable-x86_64-unknown-linux-gnu (default)
rustc 1.70.0 (90c541806 2023-05-31)

I also tried with docker, but the issue is still there

**Comment by ascjones** [comment] 2023-06-12 11:01
You will need to use Rust `1.69`, there are new wasm opcodes emitted now in `1.70` that are not yet supported by `cargo-contract` and `pallet-contracts`. 

Closing as duplicate of https://github.com/paritytech/cargo-contract/issues/1139

**Closed by ascjones** 2023-06-12 11:01 UTC
