### ISSUE TITLE
associated consts cannot be referenced in patterns

### ISSUE THREAD

**Issue by abing258** [paritytech/cargo-contract#758] opened 2022-09-28 14:57 UTC
The version I use
cargo 1.64.0 (387270bc7 2022-09-16)
cargo-contract 1.5.0-unknown-aarch64-apple-darwin

When I use `cargo +nightly contract build` to compile the default contract，I got an error

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/45306202/192813070-e00a427a-d867-4a4a-aa45-a00324c238ba.png">

**Comment by xgreenx** [comment] 2022-09-28 15:14
Duplicate of https://github.com/paritytech/cargo-contract/issues/745

**Comment by abing258** [comment] 2022-09-28 15:49
> Duplicate of #745

Solved, thanks

**Closed** 2022-10-06 11:59 UTC
